const OriginalFont = {
  0: [
    [true, true, true, true],
    [true, false, false, true],
    [true, false, false, true],
    [true, false, false, true],
    [true, false, false, true],
    [true, true, true, true],
  ],
  1: [
    [false, true, true, false],
    [true, false, true, false],
    [false, false, true, false],
    [false, false, true, false],
    [false, false, true, false],
    [true, true, true, true],
  ],
  2: [
    [true, true, true, false],
    [false, false, false, true],
    [false, false, false, true],
    [false, false, true, false],
    [false, true, false, false],
    [true, true, true, true],
  ],
  3: [
    [true, true, true, true],
    [false, false, false, true],
    [false, false, false, true],
    [false, true, true, true],
    [false, false, false, true],
    [true, true, true, true],
  ],
  4: [
    [true, false, false, true],
    [true, false, false, true],
    [true, true, true, true],
    [false, false, false, true],
    [false, false, false, true],
    [false, false, false, true],
  ],
  5: [
    [true, true, true, true],
    [true, false, false, false],
    [true, false, false, false],
    [true, true, true, true],
    [false, false, false, true],
    [true, true, true, true],
  ],
  6: [
    [true, true, true, true],
    [true, false, false, false],
    [true, false, false, false],
    [true, true, true, true],
    [true, false, false, true],
    [true, true, true, true],
  ],
  7: [
    [true, true, true, true],
    [false, false, false, true],
    [false, false, false, true],
    [false, false, false, true],
    [false, false, false, true],
    [false, false, false, true],
  ],
  8: [
    [true, true, true, true],
    [true, false, false, true],
    [true, false, false, true],
    [true, true, true, true],
    [true, false, false, true],
    [true, true, true, true],
  ],
  9: [
    [true, true, true, true],
    [true, false, false, true],
    [true, true, true, true],
    [false, false, false, true],
    [false, false, false, true],
    [false, false, false, true],
  ],
  ',': [[false], [false], [false], [false], [true], [true]],
  '.': [[false], [false], [false], [false], [false], [true]],
  m: [
    [false, false, false, false, false],
    [false, false, false, false, false],
    [false, false, false, false, false],
    [true, true, true, true, true],
    [true, false, true, false, true],
    [true, false, true, false, true],
  ],
  b: [
    [true, true, true, false],
    [true, false, false, true],
    [true, false, false, true],
    [true, true, true, false],
    [true, false, false, true],
    [true, true, true, false],
  ],
  k: [
    [false, false, false, false],
    [true, false, false, false],
    [true, false, false, true],
    [true, false, true, false],
    [true, true, true, false],
    [true, false, false, true],
  ],
  $: [
    [false, false, true, false, false],
    [true, true, true, true, true],
    [true, false, true, false, false],
    [true, true, true, true, true],
    [false, false, true, false, true],
    [true, true, true, true, true],
    [false, false, true, false, false],
    [false, false, false, false, false],
  ],
};

export default OriginalFont;
